stages:
- name: Build
  steps:
  - runScriptConfig:
      image: php:latest
      shellScript: |-
        php -v
        lsb_release -d
        sudo apt-get install -f composer
        #uname -a
        #composer -v
timeout: 60
notification: {}
